stages:
  - lint
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run check:format

deploy:
  image: node:14.17.0-alpine
  stage: build
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
    - dpl --provider=heroku --app=intense-escarpment-58932 --api_key=$HEROKU_API_KEY
    - echo "Deploy to server"
