stages:
  - lint
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run check:format

deploy:
  image: node:14.17.0-alpine
  stage: build
  script:
    - apk update && apk add git
    - gem install heroku
    - heroku auth:token
    - git push 'https://git.heroku.com/intense-escarpment-58932.git' HEAD:main
    - echo "Deploy to server"
