stages:
  - lint
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run check:format

deploy:
  image: node:14.17.0-alpine
  stage: build
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/intense-escarpment-58932.git HEAD main
    - echo "Deploy to server"