name: Create review app

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to the server
        run: |
          rsync -a -r --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --include-from .deploylist \
          --exclude public \
          --exclude ecosystem.config.js \
          . deploy@157.230.31.116:~/app/${{ github.head_ref }}/
      - name: Restarting the app
        run: |
          ssh $SSH_USER@$SSH_HOST "cp ~/ecosystem.config.js ~/app/${{ github.head_ref }}/ && pushd ~/app/${{ github.head_ref }} && sed -i 's/realworld-db/${{ github.head_ref }}/' ecosystem.config.js && ./bin/create-db-copy ${{ secrets.DB_PASSWORD }} ${{ github.head_ref }} && npm install && pm2 restart ecosystem.config.js --name ${{ github.head_ref }} --env production --update-env && popd"
        env:
         SSH_USER: ${{ secrets.SSH_USER }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Post review app URL
        if: success()
        uses: mshick/add-pr-comment@v1
        with:
          message: Created new review app at ${{ env.REVIEW_APP_URL }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          REVIEW_APP_URL: http://${{ github.head_ref }}.${{ secrets.APP_HOST }}/